name: Publish new Versions
on:
  push:
    branches:
      - main
      - ci/*
env:
  CI: true
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.20.3
      
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Configure CI Git User      
        run: |
          git config --global user.name 'Danilo Velasquez'
          git config --global user.email 'danilo.velasquez@gmail.com'
          git remote set-url origin https://$GITHUB_TOKEN@github.com/dvelasquez/monorepo-pnpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up NPM credentials
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc 2> /dev/null
          npm whoami
          npm config set access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build -r      
      
      - name: version
        run: pnpm ci:version

      - name: publish
        run: pnpm ci:publish
      